# SPDX-License-Identifier: GPL-2.0
#
subdir-ccflags-y +=  -I$(srctree)/vendor/include
subdir-ccflags-y +=  -I$(srctree)/vendor/include/uapi
subdir-ccflags-y +=  -I$(srctree)/vendor/arch/arm64/include

obj-y				+= kernel/
obj-y				+= drivers/
obj-y				+= net/
obj-y				+= scripts/
