# SPDX-License-Identifier: GPL-2.0
subdir-ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_CHARGER_BQ25700)	+= bq25700_charger.o
obj-$(CONFIG_BATTERY_CW2017)	+= cw2017_battery.o
obj-$(CONFIG_BATTERY_RK817)	+= rk817_battery.o
obj-$(CONFIG_CHARGER_RK817)	+= rk817_charger.o