# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the video capture/playback device drivers.
#

obj-$(CONFIG_VIDEO_ROCKCHIP_CIF)       += cif/
obj-$(CONFIG_VIDEO_ROCKCHIP_ISP)       += isp/
obj-$(CONFIG_VIDEO_ROCKCHIP_ISPP)      += ispp/
