# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ARM_ROCKCHIP_BUS_DEVFREQ)	+= rockchip_bus.o
obj-$(CONFIG_ARM_ROCKCHIP_DMC_DEVFREQ)	+= rockchip_dmc.o rockchip_dmc_common.o
obj-$(CONFIG_PM_DEVFREQ_EVENT)          += event/
